apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-react-frontend-deployment
  namespace: develop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green-platform-react
  template:
    metadata:
      labels:
        app: green-platform-react
    spec:
      containers:
      - name: green-platform-react
        image: paperjmendoza/green-platform-react:1.0.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhubsecret-green-react