apiVersion: v1
kind: Service
metadata:
  name: green-platform-react-service
  namespace: develop
spec:
  selector:
    app: green-platform-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer